### ISSUE TITLE
Setting up a price without the item

### ISSUE THREAD

**Issue by SamSamSam1999** [Clickism/ClickShop#12]
Hi, in my server we often use shops to trade with offline players, like, creating a shop in said player house door, supplying the shop with the product and determining the price, and sometimes we don't have the item we want in return, so, is there a way to set the price without having the item?
The plugin is incredible and beautifull, keep up the good work :)

**Comment by Clickism** [comment]
This should be partially added in the rewrite. Now, if you right click the product with the same item, it will increase the amount by one similar to vanilla inventories. So if you have 1 iron, but for example want to put 10 as a price, you can keep right clicking with your 1 iron until it reaches 10. So you practically only need one of that item. 

I won't however make it so that you can set the price via a command or something (without having any of that item)
